- source:
    kind: ConfigMap
    name: pipeline-variables
    fieldPath: data.DEPLOYMENT_NAME
  targets:
  - select:
      kind: Deployment
    fieldPaths:
    - metadata.name
    - spec.selector.matchLabels.app
    - spec.template.metadata.labels.app
    - spec.template.spec.containers.[name=DEPLOYMENT_NAME-COLOR].name
- source:
    kind: ConfigMap
    name: pipeline-variables
    fieldPath: data.COLOR
  targets:
  - select:
      kind: Deployment
    fieldPaths:
    - metadata.name
    - spec.template.spec.containers.0.name # Reference using ...containers.[name=...] like above doesn't work
    options:
      delimiter: '-'
      index: 10 # Use index greater than the length to create suffix
- source:
    kind: ConfigMap
    name: pipeline-variables
    fieldPath: data.COLOR
  targets:
  - select:
      kind: Deployment
    fieldPaths:
    - spec.selector.matchLabels.col
    - spec.template.metadata.labels.col
- source:
    kind: ConfigMap
    name: pipeline-variables
    fieldPath: data.HTTP_LISTEN_PORT
  targets:
  - select:
      kind: Deployment
    fieldPaths:
    - spec.template.spec.containers.0.ports.0.containerPort
    - spec.template.spec.containers.0.livenessProbe.httpGet.port
    - spec.template.spec.containers.0.readinessProbe.httpGet.port
- source:
    kind: ConfigMap
    name: pipeline-variables
    fieldPath: data.PVC_NAME
  targets:
  - select:
      kind: Deployment
    fieldPaths:
    - spec.template.spec.volumes.0.persistentVolumeClaim.claimName
