# Default profile
spring:
    mvc:
        pathmatch:
            matching-strategy: ant-path-matcher
    thymeleaf:
        enable-spring-el-compiler: true

server:
    servlet:
        context-path: "/geoclient/v2"

logging:
    group:
        geoclient-all:
            - "gov.nyc.doitt.gis.geoclient"
        geoclient-jni:
            - "gov.nyc.doitt.gis.geoclient.jni"
        geoclient-core:
            - "gov.nyc.doitt.gis.geoclient.api"
            - "gov.nyc.doitt.gis.geoclient.cli"
            - "gov.nyc.doitt.gis.geoclient.config"
            - "gov.nyc.doitt.gis.geoclient.function"
            - "gov.nyc.doitt.gis.geoclient.util"
        geoclient-parser:
            - "gov.nyc.doitt.gis.geoclient.parser"
        geoclient-sanitizer:
            - "gov.nyc.doitt.gis.geoclient.service.sanitizer"
        geoclient-service:
            - "gov.nyc.doitt.gis.geoclient.service"
        spring-all:
            - "org.springframework"
        spring-boot:
            - "org.springframework.boot"
        spring-web:
            - "org.springframework.web"
        thymeleaf:
            - "org.thymeleaf"
        thymeleaf-trace:
            - "org.thymeleaf.TemplateEngine.CONFIG"
            - "org.thymeleaf.TemplateEngine.TIMER"
            - "org.thymeleaf.TemplateEngine.cache.TEMPLATE_CACHE"
        tomcat-access:
            - "java.util.logging.ConsoleHandler.level"
            - "org.apache.catalina.session.level"
        tomcat:
            - "org.apache.catalina"
            - "org.apache.coyote"
            - "org.apache.tomcat"
    level:
        root: "WARN"
        geoclient-all: "WARN"
        geoclient-sanitizer: "INFO"
        spring-all: "WARN"

management:
    endpoints:
        enabled-by-default: false
---
spring:
    config:
        activate:
            on-profile: "accesslog"
logging:
    level:
        geoclient-all: "INFO"
        spring-all: "INFO"
        tomcat-access: "TRACE"
server:
    tomcat:
      basedir: "/workspaces/tomcat"
      accesslog:
          check-exists: true
          directory: "logs"
          enabled: true
          suffix: ".log"
---
spring:
    config:
        activate:
            on-profile: "quiet"
logging:
    level:
        spring-all: "ERROR"
        geoclient-all: "ERROR"
---
spring:
    config:
        activate:
            on-profile: "bootRun"
    mvc:
        log-request-details: true
logging:
    level:
        spring-all: "INFO"
        geoclient-service: "INFO"
    file:
        name: "build/bootrun/logs/geoclient.log"
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
---
spring:
    config:
        activate:
            on-profile: "docsamples"
    jackson:
        serialization:
            indent-output: true
    mvc:
        log-request-details: true
logging:
    level:
        spring-all: "INFO"
        geoclient-service: "INFO"
    file:
        name: "build/docsamples/logs/geoclient.log"
management:
  endpoint:
    shutdown:
        enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
