spring:
    mvc:
        contentnegotiation:
            favor-path-extension: true
            favor-parameter: false
    thymeleaf:
        enable-spring-el-compiler: true

server:
    servlet:
        context-path: "/geoclient/v2"

logging:

    group:
        geoclient:
            - "gov.nyc.doitt.gis.geoclient"
        geoclient-jni:
            - "gov.nyc.doitt.gis.geoclient.jni"
        geoclient-service:
            - "gov.nyc.doitt.gis.geoclient.service"
        spring:
            - "org.springframework"
        spring-boot:
            - "org.springframework.boot"
        spring-web:
            - "org.springframework.web"
        thymeleaf:
            - "org.thymeleaf"
        thymeleaf-trace:
            - "org.thymeleaf.TemplateEngine.CONFIG"
            - "org.thymeleaf.TemplateEngine.TIMER"
            - "org.thymeleaf.TemplateEngine.cache.TEMPLATE_CACHE"
        tomcat:
            - "org.apache.catalina, org.apache.coyote"
            - "org.apache.tomcat"

    level:
        root: "WARN"
        spring: "INFO"
        spring-boot: "INFO"
        spring-web: "INFO"
        thymeleaf: "INFO"
        thymeleaf-trace: "INFO"
        tomcat: "INFO"
        geoclient: "INFO"
        geoclient-jni: "DEBUG"
        geoclient-service: "INFO"
        ## Log Dozer bean mapping framework
        #com.github.dozermapper: "DEBUG"
        ## Log XML deserialization into workarea fields at startup
        #gov.nyc.doitt.gis.geoclient.config.xml: "DEBUG"
        ## Log native C runtime and JNI configuration at startup
        #gov.nyc.doitt.gis.geoclient.jni: "DEBUG"
        ## Log character buffer values from geosupport requests/repsonses
        #gov.nyc.doitt.gis.geoclient.function.GeosupportFunction: "TRACE"
        ## Log request/response HashMaps before/after geosupport call
        #gov.nyc.doitt.gis.geoclient.service.invoker.GeosupportServiceImpl: "DEBUG"

management:
    endpoints:
        enabled-by-default: false
---
#
# Command line for using this profile with the gradle bootRun task:
#
# ./gradlew -Dgc.jni.version=geoclient-jni-2 bootRun --args='--spring.profiles.active=bootRun'
#
spring:
    profiles: bootRun
server:
    tomcat:
      basedir: "@bootRunDir@"
      accesslog:
          directory: logs
          enabled: true
          pattern: "%t %a \"%r\" %s (%D ms)"
          prefix: access_
logging:
    level:
        spring: "INFO"
        spring-boot: "INFO"
        spring-web: "INFO"
        thymeleaf: "INFO"
        #thymeleaf-trace: "TRACE"
        #gov.nyc.doitt.gis.geoclient: "INFO"
        ## Log native C runtime and JNI configuration at startup
        gov.nyc.doitt.gis.geoclient.jni: "DEBUG"
        ## Log character buffer values from geosupport requests/repsonses
        gov.nyc.doitt.gis.geoclient.function.GeosupportFunction: "TRACE"
    file:
        name: "@bootRunDir@/logs/geoclient.log"

management:
    endpoints:
        enabled-by-default: true
        web:
            exposure:
                include: "*"
