spring:
    mvc:
        # The following is currently done in WebConfig.java:
        #contentnegotiation:
        #    favor-path-extension: true
        #    favor-parameter: false
        #    ignore-accept-header: true
        #    use-jaf: false
        pathmatch:
            use-suffix-pattern: true
            matching-strategy: ant-path-matcher
#           use-registered-suffix-pattern: false
    thymeleaf:
        enable-spring-el-compiler: true

server:
    servlet:
        context-path: "/geoclient/v2"
        # As of spring-boot v2.4, DefaultServlet not registered by default. See:
        # https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes#default-servlet-registration
        # TODO: Investigate why this is required for geoclient-service
        #register-default-servlet: true

logging:
    group:
        geoclient-all:
            - "gov.nyc.doitt.gis.geoclient"
        geoclient-jni:
            - "gov.nyc.doitt.gis.geoclient.jni"
        geoclient-core:
            - "gov.nyc.doitt.gis.geoclient.api"
            - "gov.nyc.doitt.gis.geoclient.cli"
            - "gov.nyc.doitt.gis.geoclient.config"
            - "gov.nyc.doitt.gis.geoclient.function"
            - "gov.nyc.doitt.gis.geoclient.util"
        geoclient-service:
            - "gov.nyc.doitt.gis.geoclient.service"
        spring-all:
            - "org.springframework"
        spring-boot:
            - "org.springframework.boot"
        spring-web:
            - "org.springframework.web"
        thymeleaf:
            - "org.thymeleaf"
        thymeleaf-trace:
            - "org.thymeleaf.TemplateEngine.CONFIG"
            - "org.thymeleaf.TemplateEngine.TIMER"
            - "org.thymeleaf.TemplateEngine.cache.TEMPLATE_CACHE"
        tomcat:
            - "org.apache.catalina, org.apache.coyote"
            - "org.apache.tomcat"

    level:
        root: "WARN"
        #spring-all: "INFO"
        #spring-boot: "INFO"
        #spring-web: "INFO"
        #thymeleaf: "INFO"
        #thymeleaf-trace: "TRACE"
        #tomcat: "INFO"
        geoclient-all: "INFO"
        ## Log native C runtime and JNI configuration at startup
        #geoclient-jni: "DEBUG"
        ## Log XML deserialization into workarea fields at startup
        #gov.nyc.doitt.gis.geoclient.config.xml: "DEBUG"
        ## Log character buffer values from geosupport requests/repsonses
        #gov.nyc.doitt.gis.geoclient.function.GeosupportFunction: "TRACE"
        ## Log request/response HashMaps before/after geosupport call
        #gov.nyc.doitt.gis.geoclient.service.invoker.GeosupportServiceImpl: "DEBUG"

management:
    endpoints:
        enabled-by-default: false
---
#
# Command line for using this profile with the gradle bootRun task:
#
# ./gradlew -Dgc.jni.version=geoclient-jni-2 bootRun --args='--spring.profiles.active=bootRun'
#
spring:
    config:
        activate:
            on-profile: "bootRun"
    mvc:
        log-request-details: true

server:
    tomcat:
      basedir: "build/bootrun"
      accesslog:
          directory: logs
          enabled: true
          pattern: "%t %a \"%r\" %s (%D ms)"
          prefix: access_

logging:
    level:
        spring-all: "INFO"
        spring-web: "INFO"
        geoclient-service: "INFO"
    file:
        name: "build/bootrun/logs/geoclient.log"

management:
    endpoints:
        enabled-by-default: true
        web:
            exposure:
                include: "*"
