apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: geoclient-v2
  variant: minikube
namespace: gis-apps
resources:
  - ../../base
  - service.yaml
replacements:
  - path: replacement.yaml
