apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-geosupport
spec:
  capacity:
    storage: 12Gi
  accessModes:
  - ReadWriteOnce
  # The "host" in "hostPath" refers to the Minikube VM filesystem
  hostPath:
    path: /data/repo
