apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-geosupport
  namespace: gis-apps
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 6Gi
