version: "3.2"

services:
  geosupport:
    image: mlipper/geosupport-docker:latest-dvc
    volumes:
      - type: volume
        source: vol-geosupport
        target: /opt/geosupport

  geoclient:
    build:
      context: ./geoclient-service
      dockerfile: Dockerfile.debug
    volumes:
      - type: volume
        source: vol-geosupport
        target: /opt/geosupport
    ports:
      - "8000:8000"
      - "8088:8080"
volumes:
  vol-geosupport:
