#
# SYNOPSIS:
#
#     Basic image for developing geoclient with Docker.
#
#     This approach is built "FROM mlipper/geosupport-docker:<version>-onbuild"
#     providing a quick and easy way to have all 2+ Gigabytes of Geosupport
#     pre-installed.
#
#     This Docker build also allows for the use of standalone or pre-existing
#     volume containers hosting a shared, versioned Geosupport installation.
#
# IMPORTANT:
#
#     This image's base image is mlipper/geosupport-docker:<version>-onbuild.
#     When this image is built, there must be the zipped, Linux distribution
#     available in the current directory or a subdirectory.
#
#     See the "SEE ALSO" section below for more information.
#
# BUILD:
#
#     $ docker build -t mlipper/geoclient:latest -f Dockerfile.dev .
#
#     $ GSD_VERSION=18a_18.1; docker build --build-arg GSD_VERSION=$GSD_VERSION -t mlipper/geoclient:$GSD_VERSION -f Dockerfile.dev .
#
# RUN:
#
#     $ docker run --rm -ti -v "$PWD":/app mlipper/geoclient
#
# SEE ALSO:
#
#     For additional information and options about  working with a Dockerized
#     Geosupport application see: https://github.com/mlipper/geosupport-docker
#
ARG GSD_VERSION=latest
FROM mlipper/geosupport-docker:${GSD_VERSION}-onbuild


RUN apt-get update && apt-get install -y --no-install-recommends \
    libc6-dev \
    gcc \
    g++ \
    openjdk-8-jdk \
    vim \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-openjdk-amd64

WORKDIR /app

VOLUME ["$GEOSUPPORT_HOME"]

CMD /bin/bash
