version: '3'
services:
  geoclient:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - geosupport:/opt/geosupport
    ports:
      - "5005:5005"
      - "8080:8080"
      - "8000:8000"
volumes:
  geosupport:
    external:
      name: geosupport
