- source:
    kind: ConfigMap
    name: pipeline-variables
    fieldPath: data.ENVIRONMENT
  targets:
  - select:
      kind: Deployment
    fieldPaths:
    - metadata.labels.environment
  - select:
      kind: HorizontalPodAutoscaler
    fieldPaths:
    - metadata.labels.environment
  - select:
      kind: Service
    fieldPaths:
    - metadata.labels.environment
- source:
    kind: ConfigMap
    name: pipeline-variables
    fieldPath: data.SVC_PORT
  targets:
  - select:
      kind: Service
    fieldPaths:
    - spec.ports.0.port
- source:
    kind: ConfigMap
    name: pipeline-variables
    fieldPath: data.SVC_TYPE
  targets:
  - select:
      kind: Service
    fieldPaths:
    - spec.type
- source:
    kind: ConfigMap
    name: pipeline-variables
    fieldPath: data.HPA_AVG_UTILIZATION
  targets:
  - select:
      kind: HorizontalPodAutoscaler
    fieldPaths:
    - spec.metrics.0.resource.target.averageUtilization
- source:
    kind: ConfigMap
    name: pipeline-variables
    fieldPath: data.HPA_MIN_REPLICAS
  targets:
  - select:
      kind: HorizontalPodAutoscaler
    fieldPaths:
    - spec.minReplicas
- source:
    kind: ConfigMap
    name: pipeline-variables
    fieldPath: data.HPA_MAX_REPLICAS
  targets:
  - select:
      kind: HorizontalPodAutoscaler
    fieldPaths:
    - spec.maxReplicas