apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: DEPLOYMENT_NAME-COLOR
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: DEPLOYMENT_NAME-COLOR
  minReplicas: -1 # MIN_REPLICAS
  maxReplicas: -1 # MAX_REPLICAS
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50