- source:
    kind: ConfigMap
    name: pipeline-variables
    fieldPath: data.DEPLOYMENT_NAME
  targets:
  - select:
      kind: HorizontalPodAutoscaler
    fieldPaths:
    - metadata.name
    - spec.scaleTargetRef.name
  - select:
      kind: Service
    fieldPaths:
    - metadata.name
    - spec.selector.app
- source:
    kind: ConfigMap
    name: pipeline-variables
    fieldPath: data.COLOR
  targets:
  - select:
      kind: HorizontalPodAutoscaler
    fieldPaths:
    - metadata.name
    - spec.scaleTargetRef.name
    options:
      delimiter: '-'
      index: 10 # Use index greater than the length to create suffix
  - select:
      kind: Service
    fieldPaths:
    - metadata.name
    options:
      delimiter: '-'
      index: 10 # Use index greater than the length to create suffix
  - select:
      kind: Service
    fieldPaths:
    - spec.selector.col
- source:
    kind: ConfigMap
    name: pipeline-variables
    fieldPath: data.MIN_REPLICAS
  targets:
  - select:
      kind: HorizontalPodAutoscaler
    fieldPaths:
    - spec.minReplicas
- source:
    kind: ConfigMap
    name: pipeline-variables
    fieldPath: data.MAX_REPLICAS
  targets:
  - select:
      kind: HorizontalPodAutoscaler
    fieldPaths:
    - spec.maxReplicas
- source:
    kind: ConfigMap
    name: pipeline-variables
    fieldPath: data.SVC_HTTP_LISTEN_PORT
  targets:
  - select:
      kind: Service
    fieldPaths:
    - spec.ports.0.port
- source:
    kind: ConfigMap
    name: pipeline-variables
    fieldPath: data.HTTP_LISTEN_PORT
  targets:
  - select:
      kind: Service
    fieldPaths:
    - spec.ports.0.targetPort