spring:
  jackson:
    serialization:
      indent-output: true
logging:
  group:
    geoclient-all: gov.nyc.doitt.gis.geoclient
    junit-condition: org.junit.jupiter.api.condition
    spring-all: org.springframework
    spring-boot-all: org.springframework.boot
  level:
    root: WARN
    geoclient-all: INFO
    #junit-condition: INFO
    #spring-all: INFO
    spring-boot-all: INFO
  file:
    name: build/integration-test.log
