services:
  geoclient:
  # Assumes run.Dockerfile has been built, tagged and pushed to
  # an accessible registry.
    image: ${GEOCLIENT_IMAGE}
    container_name: geoclient
    ports:
      - 8080:8080
    volumes:
      - geosupport-data:/opt/geosupport
    environment:
      - GEOSUPPORT_BASE=/opt/geosupport
      - GEOSUPPORT_HOME=/opt/geosupport/current
      - GEOFILES=/opt/geosupport/current/fls/
volumes:
  geosupport-data:
  # Assumes .env file or environment variable is defined with name of an
  # existing Docker volume prep-populated with Geosupport.
    name: ${GEOSUPPORT_VOLUME}

