apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/properties
  - pvc.yaml

namespace: gis-apps

components:
  - ../../components/minikube

replacements:
  - path: replacement.yaml
