apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    release-scope: pvc-only
  labels:
    app: geoclient-v2
    # Do not use col since claim may be used in blue and green releases.
    # col: COLOR
    environment: all
  name: PVC_NAME
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: csi-hostpath-sc