== Development

This section documents building Geoclient from source, the project's core architecture and several development use cases.

'''

=== Platforms

Linux x86_64:: Runs on recent kernel versions with `libc6`. Lots of successful production experience with `debian` and `RHEL`-based distros.
Windows x86_64:: Can run on Windows 10 or 11. Not recommended for production use.

=== Building from source

****
Building Geoclient from source is tricky because of the many combinations of platforms, runtimes, tools, and pre-existing Geosupport binary artifacts.

At this time, the New York City Department of City Planning only distributes binaries for Linux and Windows. The macOS platform is *not* supported.

If you have a choice, prefer building on Linux as more of the standard C/JNI conventions work as expected. It is possible to build and run Geoclient/Geosupport on Windows, but we highly recommend Linux for the best performance.

Finally, always use 64-bit versions of all software. 32-bit versions are *not* supported.
****

==== Requirements

* 64-bit Geosupport
* 64-bit JDK 17+ ("Full" JDK required. JRE by itself will *not* build)
* Gradle 8.7+
* 64-bit Linux or Windows
* 64-bit native `C` and `C&#43;&#43;` compilers: `gcc` and `g&#43;&#43;`

==== Gradle Build

.Gradle build from bash
[source,sh]
----
git clone {geoclient-repo}
cd geoclient
./gradlew build
----

=== Projects

```txt
.
`-- geoclient
    |-- buildSrc
    |-- ci
    |-- config
    |   `-- checkstyle
    |-- documentation
    |-- geoclient-core
    |-- geoclient-jni
    |-- geoclient-parser
    |-- geoclient-service
    |-- geoclient-test
    |-- geoclient-utils
    |   |-- cli
    |   `-- jni-test
    |-- gradle
    |-- images
    |-- manifests
    `-- src
        |-- scripts
        `-- spotless
```

==== geoclient-service

The `geoclient-service` project uses Spring Boot for dependency-injection
and to minimize the need boiler-plate code and configuration.
The `geoclient-service/src/main/resources/application.yaml` file is used
to configure the runtime environment and properties for different profiles.

For complete documentation of Spring Boot and the functionality configured in `application.yaml`, see:

* https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle
* https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.external-config
* https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.profiles

The default profile is specified first and active unless overridden.
Optional profiles are demarcated by lines beginning with "--"
and can add new functionality or override default properties.

NOTE: When using gradle to run the `bootRun` task provided by the `spring-boot`
plugin, the following syntax is used to specify active profiles and/or
override specific application properties managed by `spring-boot`.

For example,

[source, bash]
----
./gradlew bootRun --args='--spring.profiles.active=bootRun,accesslog --server.tomcat.basedir=/var/log'
----

WARNING: This profile should NOT be used in production environments because it
specifies a permissive configuration of Spring Actuator.

NOTE: Although no longer required, the Java system property `gc.jni.version`
can be provided on any command line. This sets the name of the subfolder in
`java.tmpdir` where the native libraries in the `geoclient-jni` jar will be unpacked.

For example, with the Gradle `bootRun` task:

[source, bash]
----
  ./gradlew -Dgc.jni.version=geoclient-jni-2 ...
----

NOTE: The following logging levels can be added to any profile,
including the default, for logging specific functionality.

geoclient-jni: "DEBUG":: Native C runtime and JNI configuration at startup.
gov.nyc.doitt.gis.geoclient.config.xml: "DEBUG":: XML deserialization into WorkArea fields at startup.
gov.nyc.doitt.gis.geoclient.function.GeosupportFunction: "TRACE":: Raw character buffer values from geosupport requests/repsonses.
gov.nyc.doitt.gis.geoclient.service.invoker.GeosupportServiceImpl: "DEBUG":: Request/response HashMaps before/after geosupport call.

NOTE: The `accesslog` profile enables HTTP request logging from the embedded Tomcat Servlet container. By default the log is written to: `/workspaces/tomcat/logs/access.log`

[source, properties]
----
<server.tomcat.basedir> = /workspaces/tomcat
<server.tomcat.accesslog.directory> = logs
<server.tomcat.suffix> = .log
----

The `<basedir>` property is relative to the system
temp directory if not given as an absolute path.
The `<accesslog.directory>` is always relative to
`<basedir>`.

Properties can be overridden at invocation time:

[source, bash]
----
--server.tomcat.basedir=...
--server.tomcat...etc.
----

If experiencing issues, insure the `tomcat-access`
logging group is defined above and set to `TRACE`
below. Also, try creating the target directory
if it does not exist before starting the app.

TODO: Define kubernetes-specific profile (https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#actuator.endpoints.kubernetes-probes).

[source, yaml]
----
management:
  endpoint:
    health:
      group:
        readiness:
          include: "readinessState"
        liveliness:
          etc...
----

=== Docker

This section explains the two most common ways to build and run `geoclient` using Docker:

* <<the-build-image,latest-build>>: builds the project from and then runs `geoclient-service`.
* <<the-run-image,latest-run>>: runs `geoclient-service` using the `geoclient.jar` built by the `geoclient-service` subproject and a local, named Docker `Volume` pre-populated with a recent Geosupport installation.

==== Assumptions

* All examples assume you have a local clone of the `geoclient` GitHub https://github.com/mlipper/geoclient.git[repository] and are running commands from the root project directory.
+
See <<building-a-docker-image-from-source,Building Docker Images>> below for details.

* Containers built from these images expect that Geosupport (`GEOSUPPORT_BASE`) is installed in `/opt/geosupport` at runtime.
* These examples start containers in the foregroung with the `-t` switch. To run `geoclient` in the background, use the `-d` switch instead.

==== Requirements

* The `geoclient` REST service (`geoclient-service`) *requires* a Geosupport installation to work.
* The examples here require the Geosupport distribution packaged by the https://github.com/mlipper/geosupport-docker[geosupport-docker] project:
 ** Compiling the `geoclient-jni` C code requires patched header files.
 ** The example ``Dockerfile``s rely on the additional management and installation features that `geosupport-docker` provides.
 ** See <<about-geosupport-docker,below>> for more details about `geosupport-docker`.

_NOTE: geoclient can use the official Linux distribution of Geosupport available from New York City's https://www.nyc.gov/site/planning/index.page[Department of City Planning]. However, additional installation and configuration steps are required._

==== Building a Docker image from source

Clone the `geoclient` from GitHub and change to the project's *root* directory.

[,sh]
----
  git clone https://github.com/mlipper/geoclient.git

  Cloning into 'geoclient'...
  remote: Enumerating objects: 11580, done.
  remote: Counting objects: 100% (2578/2578), done.
  remote: Compressing objects: 100% (904/904), done.
  remote: Total 11580 (delta 1020), reused 2463 (delta 972), pack-reused 9002
  Receiving objects: 100% (11580/11580), 10.27 MiB | 13.71 MiB/s, done.
  Resolving deltas: 100% (4942/4942), done.

  # Change to the root project directory.
  cd geoclient
----

==== The `build` image

This image installs Geosupport, builds the project from source using https://gradle.org/[Gradle], and runs geoclient.

A complete Geosupport installation is approximately 2.3 GB in size and adding it directly to the image results in both a _very_ large image and container. In general, prefer adding Geosupport via a <<creating-a-named-geosupport-volume,named volume>>.

. Build the image from the root of the project.
+
[,sh]
----
 docker build -t geoclient:latest-build -f images/build.Dockerfile .
----

. Create and run a temporary container in the background, mapping the container port `8080` to your host port `8080`.
+
[,sh]
----
 docker run --rm -t -p 8080:8080 geoclient:latest-build
----

. <<testing-the-container,Test the container>>.

==== The `run` image

Runs geoclient using the exploded contents of the https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/[spring-boot]-packaged jar built from the `geoclient-service` subproject.

. Build the `run` image from the root of the project.
+
[,sh]
----
 docker build -t geoclient:latest-run -f images/run.Dockerfile .
----
+
This assumes you are using the `geoclient.jar` jar artifact produced by the `geoclient/geoclient-service` subproject's Gradle `build` task. If the the default geoclient-service bootJar artifact `<root project>/geoclient-service/libs/geoclient.jar` is somewhere else, add a Docker build argument with the path to jar file:
+
[,sh]
----
 docker build --build-arg JARFILE=/path/to/geoclient-service.jar -t geoclient:latest-run -f images/run.Dockerfile .
----

. Follow the steps <<creating-a-named-geosupport-volume,below>> to create a local volume named `geosupport-latest`, pre-populated with the uncompressed Geosupport distribution.
. Run a temporary container, mounting the local `geosupport-latest` volume into the container at `/opt/geosupport`.
+
[,sh]
----
 docker run --rm -t --mount source=geosupport-latest,target=/opt/geosupport -p 8080:8080 geoclient:latest-run
----

. <<testing-the-container,Test the container>>.

==== Creating a named Geosupport volume

Create a local, named volume containing a Geosupport installation, using the https://github.com/mlipper/geosupport-docker[geosupport-docker] project. Use the default `GEOSUPPORT_BASE` path of `/opt/geosupport`.

[,sh]
----
   docker volume create geosupport-latest
   docker run --rm --mount source=geosupport-latest,target=/opt/geosupport mlipper/geosupport-docker:latest /bin/true
----

_See the https://github.com/mlipper/geosupport-docker/blob/main/README.md[`README`] for <<about-geosupport-docker,geosupport-docker>> for a more detailed example._

==== Docker Compose

This section assumes you've followed the instructions in <<the-run-image,The Run Image>> and <<creating-a-named-geosupport-volume,Creating a Named Geosupport Volume>> above. The following objects should be available from your local Docker registry/installation:

* The `geoclient:latest-run` image.
* The `geosupport-latest` volume.

Note that the `GEOCLIENT_IMAGE` and `GEOSUPPORT_VOLUME` environment variables are defaulted to `geoclient:latest-run` and `geosupport-latest`, respectively by the `images/.env` file.

To start the service, run the following from the geoclient project root directory:

[,sh]
----
docker compose -f images/compose.yaml up
----

To shut down the service, run:

[,sh]
----
docker compose -f images/compose.yaml down
----

==== Testing the container

Using the tool of your choice, geocode a NYC intersection. E.g., "east 53 street and 3rd avenue".

* Use `curl` from the command line
+
[,sh]
----
  curl 'http://localhost:8080/geoclient/v2/search?input=east%2053%20street%20and%203rd%20avenue'
----

* Or use a browser to open http://localhost:8080/geoclient/v2/search?input=east%2053%20street%20and%203rd%20avenue[this URL].

==== About geosupport-docker

The https://github.com/mlipper/geosupport-docker[geosupport-docker] provides an opinionated, re-packaged version of the official Linux distribution of Geosupport available from New York City's https://www.nyc.gov/site/planning/index.page[Department of City Planning]. This project's Docker images depend upon ``geosupport-docker``'s CLI scripts and patched `C` header files for installation, system configuration and native compilation tasks.

Although the `geoclient` runtime only requires that Geosupport's shared libraries are accessible to the `JVM` (via `ldconfig`, `java.library.path`, `LD_LIBRARY_PATH`, etc.) and that the `GEOFILES` environment variable is set to the absolute path (_with an appended '/' character_) of Geosupport's data files, use of `geosupport-docker`, greatly simplifies the effort of installing and managing Geosupport.


=== Kubernetes

==== Kustomize

* `build.sh`: runs kustomize and optionally parses out individual object manifests.
* `cluster-state.sh`: generates backup of existing object YAML definitions.

==== Overlays

===== Main Overlays

|===
| Path | Component | Generated Objects

| overlays/app/dev/no-pvc
| development
| deployment, hpa, service

| overlays/app/dev/pvc
| development
| deployment, hpa, service, pvc

| overlays/app/prd/no-pvc
| production
| deployment, hpa, service

| overlays/app/prd/pvc
| production
| deployment, hpa, service, pvc
|===

===== Ingress Overlays

|===
| Path | Component | Generated Objects

| overlays/ingress-nginx/dev
| development
| ingress

| overlays/ingress-nginx/prd
| production
| ingress
|===

===== PVC Overlays

|===
| Path | Component | Generated Objects

| overlays/pvc-azurefile/dev
| development
| pvc

| overlays/pvc-azurefile/prd
| production
| pvc
|===

[,sh]
----
overlays/
├── app
│   ├── dev
│   │   ├── no-pvc
│   │   └── pvc
│   └── prd
│       ├── no-pvc
│       └── pvc
├── ingress-nginx
│   ├── base
│   ├── dev
│   └── prd
├── minikube
└── pvc-azurefile
    ├── base
    ├── dev
    └── prd
----
