== History

A brief history of New York City geocoding services.

'''

For the past 30 years, the Department of City Planning (DCP) has created and maintained the **Geosupport** application. **Geosupport** is the City's official geocoder used by City agencies as the "lingua franca" for validation and standardization of New York City location data.

Until recently, Geosupport existed only on internal City mainframe systems and although it was possible to access the application there, developers of client applications running on non-mainframe systems needed to know detailed information about Geosupport's internal data structures in order to extract and parse returned location data.

In 2013, at the request of DoITT/Citywide GIS, the programmers at DCP compiled Geosupport as a native Linux C application. This allowed for the creation of **Geoclient** which uses a thin layer of C and JNI to provide a lightweight in-process Java library for calling Geosupport functions. Although Geoclient is primarily written in Java, this project also provides the code for running Geoclient as a platform-neutral web service which can be accessed through a simple REST API.

=== Geosupport Documentation

* DCP provides the [Geosupport Desktop Edition](https://www.nyc.gov/site/planning/data-maps/open-data.page#geocoding_application) as a free download.
* The Department of City Planning's [GOAT](http://nyc.gov/goat) is an HTML-based front-end for calling Geosupport.
* The [GOAT User Guide](https://a030-goat.nyc.gov/GOAT/UserGuide) provides a good introductary overview of Geosupport.
