== REST API

This section documents how to call the Geoclient REST API and provides example requests and responses.

'''

The Geoclient service provides the following endpoints:

.Endpoints
[cols="1,2,1"]
|===
|Type | Description | Geosupport Function

|Address
|Given a valid address, provides blockface-level, property-level, and political information ({dcp-goat}/Function1B[source]).
|1B{empty}footnote:1B[See {dcp-upg-cows}#work-area-2-cow-function-1b[1B]]

|Address Point
|"Function AP finds the address point for a given address. Address points are point locations located approximately five feet inside the building along the corresponding street frontage. Address points do not exist for all administrative address ranges assigned to a building, but usually only reflect the posted address." ({dcp-goat}/FunctionAP[source])
|AP{empty}footnote:AP[See {dcp-upg-cows}#work-area-2-cow-function-ap[AP]]

|BBL
|Given a valid borough, block, and lot provides property-level information. ({dcp-goat}/FunctionBL[source])
|BL{empty}footnote:BL[See {dcp-upg-cows}#work-area-2-cow-function-1a-bl-bn-extended[BL]]

|BIN
|Given a valid building identification number provides property-level information. ({dcp-goat}/FunctionBN[source])
|BN{empty}footnote:BN[See {dcp-upg-cows}#work-area-2-cow-function-1a-bl-bn-extended[BN]]

|Blockface
|Given a valid borough, "on street" and cross streets provides blockface-level information. ({dcp-goat}/Function3[source])
|3{empty}footnote:3[See {dcp-upg-cows}#work-area-2-cow-function-3[3]], 3X{empty}footnote:3X[See {dcp-upg-cows}#work-area-2-cow-function-3-extended[3X]]

|Intersection
|Given a valid borough and cross streets returns information for the point defined by the two streets. ({dcp-goat}/Function2[source])
|2{empty}footnote:2[See {dcp-upg-cows}#work-area-2-cow-function-2[2]], 2W{empty}footnote:2W[See {dcp-upg-cows}#work-area-2-cow-function-2w-wide[2W]]

|Place
|Same as 'Address' above using well-known NYC place name for input (instead of a house number and street).
|1B{empty}footnote:1B[]

|Search
|Provides parsing and search algorithm customization for several of the other endpoints listed in this section. Typically used for geocoding unstructured text to support "single-field" user searches. See link:#section-1.3[Section 1.3] for details.
|Address, BBL, BIN, Blockface, Intersection, Place

|Streetcode
|Translates a Geosupport street code (`B5SC`, `B7SC`, or `B10SC`) to a street name and `B10SC`. ({dcp-goat}/FunctionD[source])
|D,DG,DN{empty}footnote:D-DG-DN[See {dcp-upg-cows}#character-only-work-area-1-cow-all-functions[D, DG, DN]]

|Normalize
|Normalizes a street name (but does *not* verify that it actually exists. {dcp-goat}/FunctionN[source])
|N{empty}footnote:N[See {dcp-upg-cows}#character-only-work-area-1-cow-all-functions[N]]

|Version
|Provides software version information about the Geoclient endpoint itself and Geosupport version/release info directly from the Geosupport instance this endpoint is currently using.
|HR (undocumented Geosupport metadata function)
|===

[#calling-the-geoclient-api]
=== Calling the Geoclient API

==== Requests

All requests are made as simple `HTTP GET` requests with input arguments specified as URL query string and/or request parameters. The service returns the `JSON` (`application/json`) media type by default unless a `Content-Type` header or the `.xml` file extension is appended as a request parameter to the endpoint function.

----
/search?input=100%20centre%20street%20manhattan <1>

/search.json?input=100%20centre%20street%20manhattan <2>
       ^^^^^

/search.xml?input=100%20centre%20street%20manhattan <3>
       ^^^^
----
<1> Returns 'JSON' (default)
<2> Returns 'JSON'
<3> Returns 'XML'

WARNING: In the example above, (2) and (3) use file extensions as request (path) parameters. This functionality is deprecated and will eventually be removed from Geoclient. In future versions, use of the `Content-Type` header will be the way to request a non-default media type.

==== Responses

Any response from Geoclient is composed almost entirely from the results of the proxied Geosupport function call. This documentation no longer attempts to provide in-depth information about these functions. Instead, links are provided to the Department of City Planning's detailed documentation about their geocoding logic and return data.

Here's some high-level guidelines that will allow your code to remain loosely coupled with this API:

* By default, Geoclient does not serialize fields returned from Geosupport with NULL values in order to reduce unecessary network I/O.
The responses shown below are for example purposes only and do not include all possible fields that may be returned.
* Even for successfully recognized input, certain data attributes may not be available for some locations. Similarly, some attributes only make sense for certain input types.
* Although the examples are "pretty-printed" in this document, calling applications should not depend on any particular formatting of responses.
* The order of returned data elements is unspecified.
* Client code which parses the structured text of a Geoclient response should not rely upon significant whitespace or element/attribute ordering.
* _However_, the field values returned by Geosupport **__sometimes do contain significant whitespace or formatting__** which Geoclient _intentionally_ leaves unchanged.
* Occasionally, Geosupport fails to recognize a valid location or there is a bug in the Geoclient code. See Section FIXME for information on when and how to contact the appropriate team.

[#auth]
=== Authentication/Authorization

Geoclient does not perform any kind of authentication or authorization. However, most hosted instances of the service run behind some kind API gateway that requires access credentials.

.Historical documentation of access API's
****
Previous versions of this document described accessing protected Geoclient servers that were hosted by the City of New York. However, since that time, more hosted endpoints using different authentication schemes have become available.

Although it is beyond the scope of this document, here's a brief summary of access methods still in use at this time:

* API authorization provided as:
** `HTTP` header:
*** `Ocp-Apim-Subscription-Key`
** `HTTP` query string parameters:
*** `app_id`
*** `app_key`

Contact your provider for signup and access instructions.
****

[#common-request]
=== Common query string and request parameters

The following request parameters are required for all operations (except where noted):

* borough (required2,3,4) parameter - must be one of the following (case-insensitive):
** Manhattan
** Bronx
** Brooklyn
** Queens
** Staten Island

=== Understanding Geoclient Return Codes

There are two ways in which the Geoclient service communicates call status information: HTTP status codes and Geosupport API return codes. The former will always be provided; the only time in which latter will not be available is when the service itself is down or system error prevents the application from returning data to the client.

HTTP return codes vs. Geosupport (application-level) return codes.

=== Endpoints

==== Address

Request:

....
/geoclient/v2/address?houseNumber=314&street=w%20100%20st&borough=manhattan
....

.Show JSON
[%collapsible]
====
[source,json,indent=0]
----
include::../samples/address-1.jsonc[tags=user_guide]
----
====

==== Address Point

Request:

....
/geoclient/v2/addresspoint?houseNumber=314&street=w%20100%20st&borough=manhattan
....

.Show JSON
[%collapsible]
====
[source,json,indent=0]
----
include::../samples/addresspoint-1.jsonc[tags=user_guide]
----
====

==== BBL

Request:

....
/geoclient/v2/bbl?borough=manhattan&block=67&lot=1
....

.Show JSON
[%collapsible]
====
[source,json,indent=0]
----
include::../samples/bbl-1.jsonc[tags=user_guide]
----
====

==== Version

Request:

....
/geoclient/v2/version.json
....

Response:

.Show JSON
[%collapsible]
====
[source,json,indent=0]
----
include::../samples/version-1.jsonc[tags=user_guide]
----
====