#!/usr/bin/bash

appdir="$HOME/workspace/geoclient"
gsbase="$HOME/lib/libgeo-devel/geosupport/current"
# These should be defined using the declared platform names in 
# geoclient/geoclient-native/build.gradle
platform=
if [[ "$(uname)" =~ "MINGW64" ]] || [[ "$(uname)" =~ "CYGWIN" ]]; then
  platform="windows_x64"
elif [[ "$(uname)" =~ "Linux" ]]; then
  platform="linux_x64"
else
  echo "Unsupported platform $(uname)"
  exit 1
fi

function addpath {
  path_to_add="$1"
  for x in "$path_to_add"; do
    case ":$PATH:" in
    *":$x:"*) :;; # already there
    *) PATH="$x:$PATH";;
    esac
  done
}

function cleanpath {
  if [ -n "$PATH" ]; then
    old_PATH=$PATH:; PATH=
    while [ -n "$old_PATH" ]; do
      x=${old_PATH%%:*}       # the first remaining entry
      case $PATH: in
      *:"$x":*) ;;         # already there
      *) PATH=$PATH:$x;;    # not there yet
      esac
      old_PATH=${old_PATH#*:}
    done
    PATH=${PATH#:}
    unset old_PATH x
  fi
}

function fix {
  exe_sh="$appdir/geoclient-native/build/install/geoclient_test/$platform/geoclient_test.sh"
  if [[ $platform =~ windows ]]; then
    exe_sh="$appdir/geoclient-native/build/install/geoclient_test/$platform/geoclient_test.bat"
    sed -i -e 's|export PATH="$gsbase/lib"|export PATH="$gsbase/lib:$PATH"|g' "$exe_sh"
  fi
  sed -i -e 's|export LD_LIBRARY_PATH="$gsbase/lib"|export LD_LIBRARY_PATH="$gsbase/lib:$LD_LIBRARY_PATH"|g' "$exe_sh"
}

function gg {
  cd $appdir
}

function gen {
  cd $appdir/geoclient-generate
}

function ntv {
  cd $appdir/geoclient-native
}

function jni {
  cd $appdir/geoclient-jni
}

function cor {
  cd $appdir/geoclient-core
}

function ppr {
  cd $appdir/geoclient-parser
}

function svv {
  cd $appdir/geoclient-service
}


unset LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$gsbase/lib
#export GC_JNI_LIBRARY_PATH=$appdir/geoclient-native/build/libs/geoclient_jni/shared
export GEOFILES=$gsbase/fls/
export GS_INCLUDE_PATH=$gsbase/include
export GS_LIBRARY_PATH=$gsbase/lib

if [[ ! -d $JAVA_HOME ]]; then
  echo "JAVA_HOME '$JAVA_HOME' does not exist"
  exit 1
fi

addpath "$JAVA_HOME/bin"
addPath "$GS_LIBRARY_PATH"
cleanpath
echo "[ENV]"
echo "[ENV] PATH=$PATH"
echo "[ENV] JAVA_HOME=$JAVA_HOME"
echo "[ENV] GRADLE_HOME=$GRADLE_HOME"
echo "[ENV] --"
echo "[ENV] GEOFILES=$GEOFILES"
echo "[ENV] --"
echo "[ENV] GS_INCLUDE_PATH=$GS_INCLUDE_PATH"
echo "[ENV] GS_LIBRARY_PATH=$GS_LIBRARY_PATH"
echo "[ENV] LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
echo "[ENV] --"
echo "[ENV] appdir=$appdir"
echo "[ENV] gsbase=$gsbase"
echo "[ENV]"
