apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../properties
  - deployment.yaml
  - service.yaml
  - hpa.yaml

configMapGenerator:
- name: pipeline-variables
  envs:
  - pipeline.env
  behavior: merge
- name: runtime-environment
  envs:
  - runtime.env

images:
- name: docker.io/mlipper/geosupport-docker
  newTag: 2.0.19
- name: docker.io/mlipper/geoclient
  newTag: 2.0.1-rc.2

namespace: gis-apps

labels:
  - pairs:
      app: geoclient-v2
      # The value of col label must match value of COLOR
      # in base/properties/pipeline.env
      col: green
    includeSelectors: true
    includeTemplates: true

replacements:
  - path: replacement.yaml
