# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- pipeline

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  group: geosupport-environment

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile.build'
        tags: |
          $(tag)
    - task: PublishTestResults@2
      inputs:
        mergeTestResults: true
        testRunner: JUnit
        testResultsFiles: '**/TEST-*.xml'
        failTaskOnFailedTests: true