- source:
    kind: ConfigMap
    name: pipeline-variables
    fieldPath: data.ENVIRONMENT
  targets:
  - select:
      kind: Deployment
    fieldPaths:
    - metadata.labels.environment
  - select:
      kind: HorizontalPodAutoscaler
    fieldPaths:
    - metadata.labels.environment
  - select:
      kind: Service
    fieldPaths:
    - metadata.labels.environment