/*
 * Copyright 2013-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package gov.nyc.doitt.gis.geoclient.test;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.ElementType.TYPE;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

import java.lang.annotation.Documented;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
/**
 * Composed annotation indicating that this type or method requires
 * a running {@code geoclient-service} instance in order for the test to be
 * executed.
 * <p>
 * Currently, used by the {@code documentation} project to create sample HTTP
 * requests and responses for documentation generated by {@code asciidoctor}.
 * <p>
 * To enforce the above, this type is composed from the following
 * {@code JUnit 5} annotation's configured as follows:
 * <ul>
 * <li>{@code @EnabledIfEnvironmentVariable(named = "GEOCLIENT_SERVICE_STATUS", matches = "(running|RUNNING)$")}</li>
 * <li>{@code @EnabledIfSystemProperty(named = "geoclient.service.status", matches = "(running|RUNNING)$")}</li>
 * </ul>
 *
 * @author mlipper
 *
 * @since 2.0
 *
 * @see org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable
 * @see org.junit.jupiter.api.condition.EnabledIfSystemProperty
 *
 */
@Retention(RUNTIME)
@Target({ TYPE, METHOD })
@Documented
@EnabledIfEnvironmentVariable(named = "GEOCLIENT_SERVICE_STATUS", matches = "(running|RUNNING)")
@EnabledIfSystemProperty(named = "geoclient.service.status", matches = "(running|RUNNING)")
public @interface RequiresRestService {

}
