# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: sample-generator
  main:
    web-application-type: none
    banner-mode: off
  jackson:
    serialization:
      indent-output: true
#generator:
#  base-url: ''
#  output-dir: ''
logging:
  group:
    geoclient-all: gov.nyc.doitt.gis.geoclient
    spring-all: org.springframework
  level:
    root: WARN
    geoclient-all: INFO
    spring-all: INFO
